export 'departamento_repository.dart';
export 'ciudad_repository.dart';
export 'barrio_repository.dart';
export 'tipo_reclamo_repository.dart';
export 'reclamo_repository.dart';
export 'consulta_facturas_repository.dart';
export 'consulta_documento_repository.dart';
export 'mi_cuenta_registro_repository.dart';
export 'olvido_contrasenha_repository.dart';